# Generated by Django 3.0.7 on 2020-08-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=200)),
                ('tutorial_published', models.DateTimeField(verbose_name='date published')),
                ('tutorial_content', models.TextField()),
            ],
        ),
    ]
