# Generated by Django 3.0.7 on 2020-08-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='tutorial_content',
            new_name='notice_content',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='tutorial_published',
            new_name='notice_published',
        ),
    ]
