# Generated by Django 3.0.7 on 2020-08-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_educatorsdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educatorsdata',
            old_name='educators_name',
            new_name='educators_title',
        ),
    ]
